import type { GapItem, GraphEdge, GraphNode, Recommendation, Snapshot } from "./api";

export const snapshot: Snapshot = {
  employees: 1000,
  technical_profiles: 420,
  adjacent_skills: 185,
  internal_candidates: 74,
  critical_gaps: 6,
  upskill: 48,
  reskill: 16,
  hire: 10,
};

export const exampleCapability = [
  { skill: "Embedded C", value: 82 },
  { skill: "Python", value: 74 },
  { skill: "ML", value: 48 },
  { skill: "Computer Vision", value: 31 },
  { skill: "Edge AI", value: 17 },
  { skill: "FPGA", value: 24 },
];

export const mockGaps: GapItem[] = [
  { skill: "Edge AI", current: 17, required: 80, gap: 63, severity: "Critical" },
  { skill: "FPGA", current: 24, required: 70, gap: 46, severity: "Critical" },
  { skill: "Computer Vision", current: 31, required: 68, gap: 37, severity: "Critical" },
  { skill: "Machine Learning", current: 48, required: 72, gap: 24, severity: "Moderate" },
  { skill: "Python", current: 74, required: 70, gap: 0, severity: "Emerging" },
  { skill: "Embedded C", current: 82, required: 75, gap: 0, severity: "Emerging" },
];

export const mockRecs: Recommendation[] = [
  {
    employee_id: "104",
    name: "A. Raman",
    current_role: "Firmware Engineer",
    target_role: "Edge AI Engineer",
    action: "Upskill",
    department: "Engineering",
    readiness: "High",
    similarity: 0.68,
    missing_skills: ["Edge AI", "FPGA"],
  },
  {
    employee_id: "156",
    name: "P. Chen",
    current_role: "Computer Vision Engineer",
    target_role: "Edge AI Engineer",
    action: "Upskill",
    department: "AI",
    readiness: "High",
    similarity: 0.64,
    missing_skills: ["FPGA", "Embedded C"],
  },
  {
    employee_id: "118",
    name: "M. Iyer",
    current_role: "ML Engineer",
    target_role: "Edge AI Engineer",
    action: "Reskill",
    department: "AI",
    readiness: "Moderate",
    similarity: 0.58,
    missing_skills: ["Embedded C", "FPGA"],
  },
  {
    employee_id: "131",
    name: "S. Kapoor",
    current_role: "FPGA Engineer",
    target_role: "Edge AI Engineer",
    action: "Upskill",
    department: "Hardware",
    readiness: "Moderate",
    similarity: 0.52,
    missing_skills: ["Computer Vision", "Python"],
  },
  {
    employee_id: "201",
    name: "J. Thomas",
    current_role: "FPGA Engineer",
    target_role: "Edge AI Engineer",
    action: "Hire",
    department: "Hardware",
    readiness: "Developing",
    similarity: 0.31,
    missing_skills: ["Edge AI", "Computer Vision", "Python"],
  },
  {
    employee_id: "142",
    name: "N. Desai",
    current_role: "Firmware Engineer",
    target_role: "Edge AI Engineer",
    action: "Reskill",
    department: "Engineering",
    readiness: "Moderate",
    similarity: 0.45,
    missing_skills: ["Edge AI", "Computer Vision", "ML"],
  },
  {
    employee_id: "167",
    name: "R. Mehta",
    current_role: "VLSI Design Engineer",
    target_role: "Edge AI Engineer",
    action: "Reskill",
    department: "Semiconductor",
    readiness: "Developing",
    similarity: 0.38,
    missing_skills: ["Edge AI", "Python", "Computer Vision"],
  },
  {
    employee_id: "178",
    name: "L. Banerjee",
    current_role: "Firmware Engineer",
    target_role: "Edge AI Engineer",
    action: "Upskill",
    department: "Engineering",
    readiness: "Moderate",
    similarity: 0.49,
    missing_skills: ["Edge AI", "FPGA", "Computer Vision"],
  },
  {
    employee_id: "189",
    name: "K. Sharma",
    current_role: "ML Engineer",
    target_role: "Edge AI Engineer",
    action: "Upskill",
    department: "AI",
    readiness: "High",
    similarity: 0.62,
    missing_skills: ["Embedded C", "FPGA"],
  },
  {
    employee_id: "214",
    name: "H. Patel",
    current_role: "ML Engineer",
    target_role: "Edge AI Engineer",
    action: "Reskill",
    department: "AI",
    readiness: "Developing",
    similarity: 0.34,
    missing_skills: ["Edge AI", "Embedded C", "FPGA"],
  },
  {
    employee_id: "226",
    name: "G. Singh",
    current_role: "Firmware Engineer",
    target_role: "Edge AI Engineer",
    action: "Upskill",
    department: "Engineering",
    readiness: "High",
    similarity: 0.61,
    missing_skills: ["Edge AI", "Computer Vision"],
  },
  {
    employee_id: "238",
    name: "F. Nair",
    current_role: "Project Leadership",
    target_role: "Edge AI Engineer",
    action: "Hire",
    department: "Strategy",
    readiness: "Developing",
    similarity: 0.22,
    missing_skills: ["Edge AI", "FPGA", "Computer Vision", "Embedded C"],
  },
];

export const mockGraph: { nodes: GraphNode[]; edges: GraphEdge[] } = {
  nodes: [
    { id: "e104", label: "A. Raman #104", type: "employee", group: "Engineering" },
    { id: "e156", label: "P. Chen #156", type: "employee", group: "AI" },
    { id: "e131", label: "S. Kapoor #131", type: "employee", group: "Hardware" },
    { id: "s1", label: "Embedded C", type: "skill", group: "Embedded" },
    { id: "s2", label: "Python", type: "skill", group: "Software" },
    { id: "s3", label: "Edge AI", type: "skill", group: "AI" },
    { id: "s4", label: "FPGA", type: "skill", group: "Hardware" },
    { id: "s5", label: "Computer Vision", type: "skill", group: "AI" },
    { id: "r1", label: "Edge AI Engineer", type: "role", group: "AI" },
    { id: "r2", label: "Firmware Engineer", type: "role", group: "Engineering" },
    { id: "p1", label: "Edge-AI Camera", type: "project", group: "Strategy" },
    { id: "p2", label: "Vision QC Pilot", type: "project", group: "AI" },
    { id: "e118", label: "M. Iyer #118", type: "employee", group: "AI" },
    { id: "e142", label: "N. Desai #142", type: "employee", group: "Engineering" },
    { id: "e189", label: "K. Sharma #189", type: "employee", group: "AI" },
    { id: "s6", label: "ML", type: "skill", group: "AI" },
    { id: "s7", label: "TensorFlow Lite", type: "skill", group: "AI" },
    { id: "r3", label: "ML Engineer", type: "role", group: "AI" },
  ],
  edges: [
    { source: "e104", target: "s1", relation: "HAS_SKILL" },
    { source: "e104", target: "s2", relation: "HAS_SKILL" },
    { source: "e104", target: "r2", relation: "IN_ROLE" },
    { source: "e104", target: "p2", relation: "WORKS_ON" },
    { source: "e156", target: "s5", relation: "HAS_SKILL" },
    { source: "e156", target: "s2", relation: "HAS_SKILL" },
    { source: "e156", target: "p1", relation: "WORKS_ON" },
    { source: "e131", target: "s4", relation: "HAS_SKILL" },
    { source: "e131", target: "p1", relation: "WORKS_ON" },
    { source: "r1", target: "s3", relation: "REQUIRES" },
    { source: "r1", target: "s4", relation: "REQUIRES" },
    { source: "r1", target: "s5", relation: "REQUIRES" },
    { source: "p1", target: "s3", relation: "REQUIRES" },
    { source: "e118", target: "s2", relation: "HAS_SKILL" },
    { source: "e118", target: "s6", relation: "HAS_SKILL" },
    { source: "e118", target: "s5", relation: "HAS_SKILL" },
    { source: "e118", target: "r3", relation: "IN_ROLE" },
    { source: "e142", target: "s1", relation: "HAS_SKILL" },
    { source: "e142", target: "s2", relation: "HAS_SKILL" },
    { source: "e189", target: "s2", relation: "HAS_SKILL" },
    { source: "e189", target: "s6", relation: "HAS_SKILL" },
    { source: "e189", target: "s7", relation: "HAS_SKILL" },
    { source: "e189", target: "r3", relation: "IN_ROLE" },
    { source: "r3", target: "s2", relation: "REQUIRES" },
    { source: "r3", target: "s6", relation: "REQUIRES" },
    { source: "r1", target: "s1", relation: "REQUIRES" },
    { source: "p2", target: "s5", relation: "REQUIRES" },
  ],
};

export const demandTimeline = [
  { month: "M0", "Edge AI": 22, FPGA: 28, ML: 40, CV: 30 },
  { month: "M3", "Edge AI": 38, FPGA: 42, ML: 52, CV: 44 },
  { month: "M6", "Edge AI": 58, FPGA: 55, ML: 64, CV: 58 },
  { month: "M9", "Edge AI": 78, FPGA: 70, ML: 74, CV: 68 },
  { month: "M12", "Edge AI": 96, FPGA: 88, ML: 84, CV: 78 },
];
